import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";

function mdxTableToHtml(mdxTable) {
  const rows = mdxTable.split("\n");
  let html = "<table>\n";
  let headerRow = true;
  rows.splice(1, 1);

  for (const row of rows) {
    const cells = row.split("|").slice(1, -1);

    html += "  <tr>\n";

    for (const cell of cells) {
      if (headerRow) {
        html += "    <th>" + cell.trim() + "</th>\n";
      } else {
        html += "    <td>" + cell.trim() + "</td>\n";
      }
    }

    headerRow = false;
    html += "  </tr>\n";
  }

  html += "</table>";

  return html;
}
// function mdxTableToHtml(mdxTable) {
//   const rows = mdxTable.split("\n");
//   let html = "<table>\n";
//   let headerRow = true;

//   rows.splice(1, 1);
//   for (const row of rows) {
//     if (row.startsWith("|") && row.endsWith("|")) {
//       const cells = row.split("|").slice(1, -1);

//       html += "  <tr>\n";

//       for (const cell of cells) {
//         if (headerRow) {
//           html += "    <th>" + cell.trim() + "</th>\n";
//         } else {
//           html += "    <td>" + cell.trim() + "</td>\n";
//         }
//       }

//       headerRow = false;
//       html += "  </tr>\n";
//     } else if (row.startsWith("|")) {
//       headerRow = true;
//     }
//   }

//   html += "</table>";

//   return html;
// }

export default function Home() {
  const [mdxTable, setMdxTable] = useState(`| 1 | 2 | 3 |`);
  const [htmlTable, setHtmlTable] = useState(mdxTableToHtml(mdxTable));
  useEffect(() => {
    setHtmlTable(mdxTableToHtml(mdxTable));
  }, [mdxTable]);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div
          style={{
            display: "flex",
            flexDirection: "row",
            width: "100%",
            height: "100vh",
          }}
        >
          <textarea
            style={{ width: "100%", height: "100%" }}
            onChange={(e) => setMdxTable(e.target.value)}
            value={mdxTable}
          />
          <textarea
            style={{ width: "100%", height: "100%" }}
            value={htmlTable}
          />
        </div>
      </main>
    </>
  );
}
